apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patch:
  - target:
      kind: Deployment
      name: backend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /metadata/labels/env
        value: stage
      - op: replace
        path: /spec/template/metadata/labels/env
        value: stage
  - target:
      kind: Deployment
      name: frontend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /metadata/labels/env
        value: stage
      - op: replace
        path: /spec/template/metadata/labels/env
        value: stage
