apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patch:
  - target:
      kind: Deployment
      name: backend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /metadata/labels/env
        value: prod
      - op: replace
        path: /spec/template/metadata/labels/env
        value: prod
  - target:
      kind: Deployment
      name: frontend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /metadata/labels/env
        value: prod
      - op: replace
        path: /spec/template/metadata/labels/env
        value: prod
