apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kubernetes-cluster-provisioner
  title: Kubernetes Cluster Provisioner
  description: Provisions a new Kubernetes cluster using Infrastructure as Code.
  tags:
    - kubernetes
    - infrastructure
    - cloud
spec:
  owner: guests
  type: infrastructure

  parameters:
    - title: Cluster Information
      required:
        - cluster_name
        - cloud_provider
        - region
      properties:
        cluster_name:
          title: Cluster Name
          type: string
          description: Unique name for the Kubernetes cluster.
          ui:autofocus: true
        cloud_provider:
          title: Cloud Provider
          type: string
          enum:
            - aws
            - azure
            - gcp
          ui:widget: radio
        region:
          title: Region
          type: string
          description: Cloud region where the cluster will be provisioned.

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          cluster_name: ${{ parameters.cluster_name }}
          cloud_provider: ${{ parameters.cloud_provider }}
          region: ${{ parameters.region }}

    - id: create-pr
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: 'New Kubernetes Cluster: ${{ parameters.cluster_name }}'
        body: 'Provisioning a new Kubernetes cluster named ${{ parameters.cluster_name }} in ${{ parameters.region }} using ${{ parameters.cloud_provider }}.'
        branchName: 'feature/new-cluster-${{ parameters.cluster_name }}'

  output:
    links:
      - title: Pull Request
        url: ${{ steps.create-pr.output.pullRequestUrl }}
