apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kubernetes-cluster-eks
  title: AWS EKS Cluster Provisioner
  description: Provisions a new AWS EKS Kubernetes cluster with end-to-end security.
  tags:
    - kubernetes
    - aws
    - eks
    - infrastructure
    - security
spec:
  owner: guests
  type: infrastructure

  parameters:
    - title: Cluster Information
      required:
        - cluster_name
        - region
        - vpc_cidr
      properties:
        cluster_name:
          title: Cluster Name
          type: string
          description: Unique name for the EKS cluster.
          ui:autofocus: true
        region:
          title: AWS Region
          type: string
          description: AWS region where the cluster will be provisioned.
          default: us-east-1
        vpc_cidr:
          title: VPC CIDR Block
          type: string
          description: CIDR block for the VPC (e.g., 10.0.0.0/16).
          default: 10.0.0.0/16

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          cluster_name: ${{ parameters.cluster_name }}
          region: ${{ parameters.region }}
          vpc_cidr: ${{ parameters.vpc_cidr }}

    - id: create-pr
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: 'New AWS EKS Cluster: ${{ parameters.cluster_name }}'
        body: 'Provisioning a new AWS EKS cluster named ${{ parameters.cluster_name }} in ${{ parameters.region }} with VPC CIDR ${{ parameters.vpc_cidr }}. Includes security configurations.'
        branchName: 'feature/new-eks-cluster-${{ parameters.cluster_name }}'

  output:
    links:
      - title: Pull Request
        url: ${{ steps.create-pr.output.pullRequestUrl }}
